### ISSUE TITLE
Improve mini bar behavior so it doesn't bother when it's occluding the top area of the webpage

### ISSUE THREAD

**Issue by spartanhooah** [Quicksaver/The-Fox--Only-Better#101]
I have the "selecting another tab" box unchecked, but when I ctrl+tab through my tabs, the address bar still shows up if I haven't visited that tab before.

**Comment by Quicksaver** [comment]
Probably because you still have ".surfing to another location" enabled. When you switch to a never-visited tab, or to a tab that has changed locations in the meantime, it will show the mini bar as expected. Is this not the case for you?

**Comment by spartanhooah** [comment]
Yes, I have that option enabled. I expected that to show the bar when I visited a new page in the current tab. I guess I misunderstood.

**Comment by Quicksaver** [comment]
It also takes into account background tabs that change location in the meantime, otherwise you would only see the mini bar in the current tab and probably miss when those background tabs changed. Not-visited-yet tabs count as well, since technically it's changing locations (from "none" to "something").

**Comment by spartanhooah** [comment]
Ok. The problem I have with the changing tabs behavior is that the bar often obscures content at the top of the window. Is there a way to avoid this?

**Comment by Quicksaver** [comment]
The bar should disappear by itself after a couple of seconds, doesn't it?

At the moment there isn't any way to avoid this, honestly because I haven't run across any case (website) where the mini bar obscures anything important at the top; usually it's just a few navigation links in that area, which become readily accessible because the mini bar disappears after a couple of seconds. Is this still a bother for you? Could you give me a specific example of a webpage where it can interfere with normal browsing?

**Comment by spartanhooah** [comment]
Yeah, it goes away after a few seconds. A prime example is the Something Awful forums. They have a feature that loads the page at the first unseen post, which puts that post's text right at the top of the window.

**Comment by Quicksaver** [comment]
I'll check it out.

**Comment by Quicksaver** [comment]
I guess you need a paid account there... Could you get me a screenshot of the mini bar in this cas where it's obscuring something please?

**Comment by spartanhooah** [comment]
Ok, here you go. There's text behind the URL bar in the screenshot.

**Comment by Quicksaver** [comment]
Sorry, github doesn't accept attachments through e-mail, you'll have to either e-mail it to me directly (quicksaver@gmail.com) or visit the thread and attach it directly.

**Comment by spartanhooah** [comment]
Oh, I didn't realize the emails were going here. Here it is.
![text covered](https://cloud.githubusercontent.com/assets/6500137/7901783/ffe3fcce-0767-11e5-8838-82c577ea5584.png)

**Comment by Quicksaver** [comment]
Hmm, I see what you mean. Maybe I could add an option to dismiss the mini bar when you click/scroll/type anywhere on the page, so you don't have to wait for it to hide automatically if you don't want to. Or maybe dismiss it when pressing Escape without causing the page to stop loading (if it hasn't finished already of course). What do you think?

Here's what I can't do:
- make the mini bar "travel" to the right side in these cases; there's no easy way to "automatically" figure out when it should do this (and in your case with longer posts it wouldn't really help i guess), and it can't be done by moving the mouse over it since its elements are still supposed to be clickable.
- customizable whitelist of hosts where the mini bar isn't needed so it shouldn't appear; while this is something I am considering for the future, realistically speaking it will take some time to get to it, so it's not something you should be expecting anytime soon.

**Comment by spartanhooah** [comment]
I already scroll to view the text anyway. I think the whitelist would be the best option in the long-run. If the escape option would be quick to implement, it would be a reasonable work-around in the meantime. Thanks for the consideration!

**Comment by Quicksaver** [comment]
Hmm, adding a key/click/scroll action to dismiss the mini bar brings its own problems, even though I should still take care of them sometime... I had another simpler idea, I assume at least in that case of the Something Awful forums that you are opening that new tab from a previous Something Awful tab. Something like "in SAF tab 1" -> click some link to view most recent post -> new tab opens with the most recent post right at the top. Is this your usual case?

I ask because this situation leads me to something else that I *think* might be a better behavior than it is now: the mini bar probably doesn't need to be shown if we're switching between tabs of the same host (website). If what I described is your case, then making this change (which is actually much easier than the others) would definitely help with that, at least for now until I add all the other stuff later on.

**Comment by spartanhooah** [comment]
Yes, that is indeed my usual use-case.

**Comment by Quicksaver** [comment]
Can you give the latest beta version 1.1.14b2 a try and tell me how it works for you? I quickly added what I mentioned in my previous comment. You can find it at the top of https://addons.mozilla.org/firefox/addon/the-fox-only-better/versions/

**Comment by spartanhooah** [comment]
That works great!

**Comment by Quicksaver** [comment]
Great! Let me know if that changes for some reason. In the meantime I'll keep this thread open to track the rest of the things we discussed, so I don't forget. ;)
