### ISSUE TITLE
Toolbar Autohide 6.7.0 incompatibility

### ISSUE THREAD

**Issue by davidhedlund** [Quicksaver/The-Fox--Only-Better#102]
* Firefox 37.0.2
* The Fox, Only Better 1.1.13
* Toolbar Autohide 6.7.0

**Comment by Quicksaver** [comment]
Can you please be more specific? Are there any specific steps to reproduce this, or does it happen always? What operating system are you on, and does it also happen if you disable all your other add-ons and themes?

**Comment by davidhedlund** [comment]
@Quicksaver Apparently it is incompatible with Toolbar Autohide. I updated the issue about it.

**Comment by Quicksaver** [comment]
So, I have to ask... Why would you even want to have both add-ons enabled if they do pretty much the same thing? Add-ons that provide the same kind of functionality, like in this case, will never be able to function properly together since they will always conflict with each other.

As far as I can see, you can choose either one or the other depending on your tastes, without really losing any kind of functionality.
