### ISSUE TITLE
Timing issues (Delay)

### ISSUE THREAD

**Issue by LigetiProject** [Quicksaver/The-Fox--Only-Better#103]
Okay, we corresponded - if you can call it that - on Mozilla's site, but thought I'd come over here.

To reiterate - I have a couple problems.  Ultimately though I think they would have been solved if I had more control over the delay feature.

Essentially a good scenario is this:

Setup:  I have my PC under my TV.  I use the TV as a monitor.  I have a wireless mouse and keyboard, since I sit a good distance from the screen.  I can use the keyboard, but for the most part I'm just clicking links etc, so often don't even pick it up.

With this add-on, the address bar is taken away, and of course slips down when needed.  A perfect example of what doesn't really work for me is when I want to refresh a page.  I can either click on the refresh button in the address bar (not optimal) or right-click the tab, and choose refresh from there.  Given how I use a computer, the latter option is better.

However, the bar then comes down.  Perhaps I'm slow.  LOL.  When the bar comes down, it obscures the group links in Speed Dial.  So not only has the bar come down when it didn't need to (I was just wanting to refresh) but I have to wait for it to go away again in order to click on a different group.

I hope that explains things.  I'd prefer a simple timer box in the interface, rather than an arbitrary LOW - FAST option.  

I don't think there's a bug in your software at all - it's my usage pattern that's causing the issue.

**Comment by Quicksaver** [comment]
When you right click on a tab to reload, sure the toolbars can show up if you take a little bit there with the mouse (I think I'll still raise the High value, as obviously in your case with the TV monitor further away it could help), but if you're going to reload a page, how does that affect the links visibility in the Speed Dial tab?

Maybe I'm missing the point, after all I don't think it makes sense to refresh Speed Dial at all... What exactly do you mean when you say "obscure the group links in Speed Dial"? Which links? If the links are in the tab you're refreshing, won't they go away anyway? Or are you refreshing a background tab? (a screenshot would be great, just to make sure we're talking about the same thing).

Also, after reading this I noticed something else. Right clicking a tab shouldn't keep the toolbars shown at all, basically they should only be visible while the mouse is over the tab itself, if you move it away from the tabs, even without closing the tab's context menu, the toolbars should hide; doesn't this happen for you?

What I did notice is that the toolbars don't hide while the mouse is over the context menu, you need to move the mouse outside of that menu, over the webpage itself, and that is a bug that I have to fix since moving it over the menu should hide the toolbars. ;) But that shouldn't really have much to do with your problem though...
