### ISSUE TITLE
1.3b2 style issue

### ISSUE THREAD

**Issue by atomGit** [Quicksaver/The-Fox--Only-Better#115]
hi LuÃ­s

this is with Slim Chrome disabled (win 7, ff 40.0.2)

as soon as i installed the 1.3b2, i noticed a slight change in the position of the elements in the nav bar - you'll notice in the screen cap that the search bar and tab above it run together

http://s6.postimg.org/bem4p5vkx/screenshot_207.png

actually, if you very closely, they overlap a few pixels...

http://s6.postimg.org/o7a8p376l/screenshot_208.png

disabling and restarting ff didn't help - it's as though there's some css that's remaining ???

part of the problem appears to be with `layout.css.devPixelsPerPx` which i have changed from it's default of -1.0 to 1.1 to zoom the entire browser and all content 

if you are not already aware of this, let me know before you look into it and i'll do some troubleshooting on my end first

**Comment by Quicksaver** [comment]
That's weird, I assume it's not supposed to look like that (I ask because I don't know that theme, and personally it doesn't look that bad for an effect of the tabs running into the location/search bars).

If you disabled the add-on, any CSS (or any other piece of code) remaining would only happen **if** it failed to disable somehow. A restart of Firefox should always fix that.

You may indeed have to do some extra troubleshooting, in particular if you can see anything of the sort without that theme enabled (I tried changing devPixelsPerPx like you but it looks fine for me, except of course bigger as intended). A try on a clean profile might also help tell if it's a conflict with another add-on as well.

**Comment by atomGit** [comment]
this does not appear to be an issue TFOB at this point - i haven't troubleshooted this to it's end, but certainly don;t worry about it - i'll let you close this if you want

thanks!

and where is your donate link? i lost it :)

**Comment by Quicksaver** [comment]
I don't mind keeping this open for now, at least until you're more sure of what is causing it, although like you I also don't believe it's TFOB (soon to have a new name ;) ).

And it's in the [add-on homepage](https://addons.mozilla.org/firefox/addon/the-fox-only-better/), I greatly appreciate it! :)

**Comment by atomGit** [comment]
ah jeez - you mean that BIG BLUE button?

LOL

----- Original Message -----
Subject: Re: [The-Fox--Only-Better] 1.3b2 style issue (#115)
Date: Fri, 04 Sep 2015 12:24:25 -0700
From: Luís Miguel <notifications@github.com>

I don't mind keeping this open for now, at least until you're more sure 
of what is causing it, although like you I also don't believe it's TFOB 
(soon to have a new name ;) ).

And it's in the [add-on 
homepage](https://addons.mozilla.org/firefox/addon/the-fox-only-better/), I 
greatly appreciate it! :)

---

**Comment by Quicksaver** [comment]
That's the one :) You're an awesome person, did you know?

**Comment by atomGit** [comment]
thanks, but i wouldn't have donated if you weren't awesomer :)
