### ISSUE TITLE
1.3b2 search sync feature - re-sync if query is changed on search engine page

### ISSUE THREAD

**Issue by atomGit** [Quicksaver/The-Fox--Only-Better#116]
search for "fireffox", google corrects to "firefox" - if you click on the "firefox" link on the google results page, it would be good if the search bar term were updated also

just using google as an example

**Comment by Quicksaver** [comment]
Hmm, not sure how I feel about this because of what I said in the e-mail I just sent you:

> The add-on doesn't fetch the search bar value from the url, but from the actual textbox in those results pages. Which is why I haven't yet made a "custom rules" part, because it's not as simple as getting new regex rules in there, it also needs to be pointed to the correct nodes.

I suppose the search bar could reflect the corrected value when the page is first loaded, and then change itself again to the "wrong" value if you type in google's search box and don't correct it yourself.

On the other hand, I could add something like "correct the page's search box automatically with the engine's corrections" (without of course getting rid of the corrected notice, that would always have to be there so you know it happened, along with the usual "search instead for..." links and all related stuff).

Hmmmmmmm...

**Comment by Quicksaver** [comment]
I had read this all wrong! This should be already happening of course. I'll try to fix it for the next release.

**Comment by Quicksaver** [comment]
I've uploaded beta version 1.3.1b1 if you'd like to try it out: https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.3.1b1

Let me know if you find any other similar cases.

**Comment by atomGit** [comment]
thank you my friend - been off-line for a while, so just getting around to trying this now - i'll let you know if there's any problems of course ;)
