### ISSUE TITLE
[A problem] The Bookmarks window is covered by Beyond Australis

### ISSUE THREAD

**Issue by hhplay** [Quicksaver/The-Fox--Only-Better#119]
![qq 20150912074557](https://cloud.githubusercontent.com/assets/14243357/9829244/fc498e94-592e-11e5-91b8-61b851ae01d2.jpg)
The older version doesn't like this.
This img showes the new version's mistake.

**Comment by hhplay** [comment]
![qq 20150912092415](https://cloud.githubusercontent.com/assets/14243357/9829277/14d0682e-5930-11e5-99d6-a6deefd7c817.jpg)

**Comment by Quicksaver** [comment]
It's meant to, the toolbars should cover the whole width of the window, the previous behavior of only covering the web content part didn't really have any reason to exist, and was less intuitive because the toolbars kept changing places when you opened and closed the sidebar.

As it mentions in the release notes, you can always revert back to the previous behavior if you want, by going to about:config and flipping the preference "extensions.thefoxonlybetter.slimOnlyOverContent".

The theme you're using is very weird though, I'm not sure it's supposed to look like that, in particular I wonder if the add-on is causing these:
- the tabs area being half dark half light
- the sidebar splitter shown above the toolbars

You should contact your theme's developers and see if these are something they can fix.
