### ISSUE TITLE
Allow mini bar to use the same (or a separate) chosen "Style"

### ISSUE THREAD

**Issue by emmyemi** [Quicksaver/The-Fox--Only-Better#121]
One of the only complaints I have with the mini bar's implementation is that it looks so very out of place with 3/4 of the currently available styles. Just as the top chrome can be customized, the mini bar should be this way as well; it would look and feel much better this way, in my humble opinion.

**Comment by Quicksaver** [comment]
I disagree. The purpose of the mini bar is right there in the name: "mini". It's meant to be a fast and transitive state of the interface. You're welcome to try to convince me otherwise, but I should warn you that "it might look better" won't be enough to do it. :)

Right now it's styled mostly with the Compact style, so that it is the least visually jarring it can be. I think applying either the Australis or the Spacious style would make it look more out of place, as it would make it cover extra webpage space unnecessarily. Obviously applying the Full Width style to it is just wrong, as it wouldn't be "mini" anymore.

Although I believe and respect that some users, like yourself, would prefer to see the mini bar styled as well, the main reason I don't do it is because for the Australis style it would require double the calculations for the borders. Not only would that obviously take a more or less larger toll on the processor, that's also a lot more code to maintain for, in my opinion, very little gain. And I think it would be wrong to do it for only the Spacious style and not for the Australis style (sort of a leave-no-style-behind thing).
