### ISSUE TITLE
about:thefoxonlybetter#skyLights

### ISSUE THREAD

**Issue by George8211** [Quicksaver/The-Fox--Only-Better#123]
In about:thefoxonlybetter#skyLights, the Enable Sky Lights checkbox "locks" the "show the mini bar when... surfing to another location" checkbox in the #slimChrome section. However if the surfing to another location checkbox is off, the Enable Sky Lights checkbox will lock it in the off state; it should (I guess) lock the surfing to another location checkbox in the on state regardless of what state it was in before.

Firefox 43.0a2, Beyond Australis 1.3.1

**Comment by Quicksaver** [comment]
It actually doesn't really matter in what state the checkbox is locked. The point of that lock is so that you can't disable both things at the same time. I could make it toggle on the checkbox when it's locked as you say, but for now as soon as you restart the browser (or simply disable and re-enable Slim Chrome for that matter) both checkboxes will be re-enabled anyway.

I'll probably do this eventually, but it's not something that will really change anything, so it's not very high on my priorities.

**Comment by Quicksaver** [comment]
You know what, I changed my mind. But instead of your suggestion, I went with something a little different. In short, you shouldn't be able to disable the sky lights / site identity light if the ".. when surfing to another location" is disabled, and vice-versa.

I put together a quick beta version with this change at https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.3.2b1 if you'd like to try it.
