### ISSUE TITLE
Incompatible with latest Firefox version

### ISSUE THREAD

**Issue by IDKwhattoputhere** [Quicksaver/The-Fox--Only-Better#140]
> Works with Firefox 42.0 - 45.0a1

This doesn't include the latest ESR version of Firefox.
It causes Mozilla to deliver old versions to ESR users.
I personally use ESR because I'm not interested in Mozilla's experiments or in downloading a huge update every 6 weeks. Others feel the same or are limited by organisations who can't update Firefox as frequently.

**Comment by Quicksaver** [comment]
It's true. I plan on keeping compatibility with the ESR version starting with the next one (45), however the changes to Firefox since then have been too great to re-implement compatibility with the current ESR. I hope you understand and that using an older version isn't too much of a bother to you in the meantime.

**Comment by IDKwhattoputhere** [comment]
Yes, it's alright. I can live without the new versions for now. Keep up the great work. :smiley:
