### ISSUE TITLE
[FeatureRequest] Don't ever show the URL-Bar automatically

### ISSUE THREAD

**Issue by Skillmon** [Quicksaver/The-Fox--Only-Better#142]
First of all I love your add-on! But the displaying of the URL-Bar upon opening a new site should be deactivatable (there is in fact the option in the add-on's settings but it is greyed out...). And maybe adding the option to deactivate it upon password insertion, too. I know this might be a security-issue but in my case, the current URL is shown in the status bar permanently.

Despite that your add-on is like perfect to me (using Pentadactyl so I neither use the mouse nor the URL-bar that much)!

Best regards
Skillmon

Edit: I have no idea how to set a label to this issue (would be "feature" obviously).

**Comment by Quicksaver** [comment]
Unfortunately this is not something I can do.

First of all that option is grayed out because you surely have disabled sky lights. You always need either one or the other.

Secondly, it's not only the url itself, but also the identity box which tells you if the connection is secure as you'd expect it to be (or not), in addition to several other status icons (tracking, prevented [something], requires [some action], etc) that often appear next to it depending on what webpage you're visiting. So you need at least either the mini bar or the identity box sky light enabled.

Anything that could, even just in theory, cause any security or vulnerability issue is just not allowed in an add-on. Even if it was, I personally still wouldn't add it to the add-on. So, disabling the mini bar on password fields (even with everything else) is a big no-no from that standpoint. I hope you understand.

**Comment by Skillmon** [comment]
Of course I understand. I want to deactivate it because I already have those features on a different spot (due to Pentadactyl which indicates whether the connection is secure or not in a much better way, because the colour of the whole status-bar is changing). I understand if you don't change it, because I might be the single case having this "issue" and it's just a minor flaw in the UI to me.
Anyway thanks for the fast answer.
