### ISSUE TITLE
Search bar disappearing

### ISSUE THREAD

**Issue by DotTheI** [Quicksaver/The-Fox--Only-Better#144]
Just installed the latest versions. It makes the search bar disappear

**Comment by yfdyh000** [comment]
This is new features, see https://addons.mozilla.org/firefox/addon/the-fox-only-better/, Enhance your Awesome Bar and Adaptable Search Bar.

Nevertheless, it is indeed unexpected, without the user confirmed to change the interface. Like a option off by default, or a tour. They is options enabled by default now.

**Comment by DotTheI** [comment]
Oh, I didn't notice that! Thank you!

**Comment by Quicksaver** [comment]
> Nevertheless, it is indeed unexpected, without the user confirmed to change the interface

True but only for existing users, new users should expect that from the screenshots and the add-on's description as well; the new awesome bar features are very prominent there. Since this will only be a one-time only surprise, I decided to just keep the default for existing users as well, it's not hard to disable at all anyway.

**Comment by DotTheI** [comment]
I didn't notice the setting either. Haven't checked them for months since I installed this great add-on

**Comment by Quicksaver** [comment]
That's another reason why I made it default. Many users, like you, won't really notice new things unless they actually show up. If they're changes of interest to them it could take far too long to notice them if they were disabled by default, and if they're not of interest then they're still easily disabled. :)

**Comment by DotTheI** [comment]
Smart move! Thanks a lot!
