### ISSUE TITLE
Bug in Suggestions Panel>Item style

### ISSUE THREAD

**Issue by BartG95** [Quicksaver/The-Fox--Only-Better#148]
When I disable "Search bar>Show search engines in the location bar", the "Suggestions Panel>Item style" setting doesn't have the right effect:

Rich is shown as Rich
Slim is shown as Rich, but just cut in half (both title and url are displayed in the left column, and the right column is empty) and with the "Visible items when searching" effect applied (I set it to 12)
Froggy is shown as Rich, but also with the "Visible items when searching" effect applied.

Note that while reproducing this, I also saw a possibly related bug: "Visible items when searching" does not apply when I choose Rich (even when I enable showing the search engines).

**Comment by Quicksaver** [comment]
You're right of course, this is a big lapse on my part.

> "Visible items when searching" does not apply when I choose Rich (even when I enable showing the search engines).

I can't reproduce this, it applies fine for me. Are you sure you mean "when searching" and not "when showing history"? Because that one did have a problem with not applying which I've already fixed. What exactly do you mean by "does not apply", you change the number but the number of items that appears stays the same?

**Comment by Quicksaver** [comment]
Note that it's not the total number of items, it's the number of items visible, as in all the others will still be there but you'll have to scroll the list down to see them.

**Comment by Quicksaver** [comment]
Looking back at it, it's possible that they were the same issue. Could you please give [beta version 1.4.3b1](https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.4.3b1) a try and see if any of that is still happening? Note that beta isn't signed, so you'll have to disable preference "xpinstall.signatures.required" in about:config in order to use it. You can reenable it after it updates to the final release version once I upload it or if you go back to the current version of course.

**Comment by BartG95** [comment]
> Note that while reproducing this, I also saw a possibly related bug: "Visible items when searching" does not apply when I choose Rich (even when I enable showing the search engines).

Sorry, I didn't change the number when I choose Rich. It works perfectly. Nonetheless, I think the number should not depend on the chosen style. But that is just a suggestion.

I can't try your beta version today, maybe later.

**Comment by Quicksaver** [comment]
If that's the case then there's probably no need to try as I could reproduce the rest perfectly as you described. :)

The visible items numbers will be different for each style because item sizes will be different. I chose this method because it might make it easier to switch styles and visualize better the results of that change. I'll leave it for now, but of course if it ends up being more trouble than it's worth I might change I then.
