### ISSUE TITLE
Merged awesomebar rendering issue

### ISSUE THREAD

**Issue by wldcordeiro** [Quicksaver/The-Fox--Only-Better#149]
In Ubuntu with the default theme I'm getting this as a result (the bar fades rather quick so screenshot is mid fade.)
![screenshot from 2016-02-08 13-26-32](https://cloud.githubusercontent.com/assets/580982/12897998/99ab19d4-ce67-11e5-98a1-e40f2b67029f.png)

**Comment by Quicksaver** [comment]
What version of Beyond Australis are you on? The latest 1.4.3 update is supposed to have fixed that. Also, I don't see the settings button at the end (after Google Search in that screenshot), have you removed it yourself somehow, maybe through a stylish script or another add-on?

**Comment by Quicksaver** [comment]
Or a theme even, is that the default Firefox theme? I can't tell to be honest.

**Comment by wldcordeiro** [comment]
I just bumped to 1.4.3 on Firefox dev edition default theme, fixed the icons. Still no settings button.

**Comment by Quicksaver** [comment]
That's weird. Can you even click it (try moving the mouse over where it should be)? Does it appear if you disable all your other add-ons and themes?

**Comment by Quicksaver** [comment]
Ok that was my fault. The button doesn't have an icon because it's trying to use the default icon for the settings and Firefox for Linux doesn't have this icon for when any kind of zoom factor / HiDPI resolution is applied.

 I've included this icon in the add-on, so it should fix this and any other theme (I've found a couple) that also doesn't have that icon at least in the same location as the default theme.
