### ISSUE TITLE
No way to add search plugin while showOnlyNonEmptySearchBar enabled?

### ISSUE THREAD

**Issue by yfdyh000** [Quicksaver/The-Fox--Only-Better#154]
e.g. Open https://www.yahoo.com/ to reproduce.

**Comment by Quicksaver** [comment]
I can't install it from the search bar either. I'm guessing that's because Yahoo is one of the default search engines in Firefox and it's conflicting with something because of that (the error in the console is very non-specific). You should report this to Mozilla instead.

Unless that's not what you mean, please reopen if the button not appearing in the location bar's results for you. It's right there for me:
![image1](https://cloud.githubusercontent.com/assets/802086/12984546/2dcf9eb6-d0e6-11e5-8cb7-9937009f4f42.jpg)

**Comment by yfdyh000** [comment]
Disable the pref-showOnlyNonEmptySearchBar for testing.
Open the https://www.yahoo.com/, I see the + icon on search bar. p.s. I see it in en-US Nightly with clean profile, it may be a Firefox bug.
If enabled the pref-showOnlyNonEmptySearchBar, no the + icon appear anywhere, can't to add the search plugin.

Alternate, you can see the + icon on websites in https://developer.mozilla.org/en-US/Add-ons/Creating_OpenSearch_plugins_for_Firefox#Reference_Material.

**Comment by Quicksaver** [comment]
I honestly don't understand. True, the location bar doesn't have a magnifying glass with the plus icon, because there's no where to add a plus icon in there. But you can still add the search engine. See my screenshot above, the last button is the Add Yahoo Search Engine button, it clearly has the plus icon in it.

**Comment by yfdyh000** [comment]
Oh, my bad. I have not aware it before, probably due to a lot of icons and the panel need to expand manually, as well as no background highlight or icon overlay on urlbar. I think this is due to an inertial from old interface, I will try to adapt to it.

**Comment by Quicksaver** [comment]
But it does make sense to show the plus icon somewhere in the location bar of course. I had considered it before but haven't gotten around to it yet.

**Comment by yfdyh000** [comment]
Maybe can add a plus icon to the Search Settings button to identify it? But it would be confusing to click the button. A suitable background color (or veins) for plus buttons (in suggest panel) might be a good idea.

**Comment by Quicksaver** [comment]
The plus sign will always appear above the search button that will be added of course, it wouldn't make sense to show it in the settings button or anywhere else that's shown at the same time.

What I meant was showing the plus icon somewhere in the location bar itself, even with the panel closed, so that you can see there are available engines to be added even if you're not currently typing in it (so you don't need the panel open to see it).

**Comment by yfdyh000** [comment]
While I like a plus icon with no need to expand, but I can't find a suitable position.
Make an toolbar icon in urlbar and allow be customize? It seems too heavyweight.
