### ISSUE TITLE
No apparent ways to search like domain in consolidated urlbar with keyboard only    

### ISSUE THREAD

**Issue by yfdyh000** [Quicksaver/The-Fox--Only-Better#155]
The suggestions list of urlbar no entry for search domain (like "example.org").

It's actually still there are ways, such as use mouse to click on search plugin icon (seem can't to use it with keyboard only), use a defined search keyword, even open the search website to use it.
So this issue is just an thinking and a reminder if you have not thought of that.
It sounds like it is not a common usage, but it does break my habit of some operations (Press Ctrl+K, search anything after press Enter key). Sorry to bother you for a less usage.

**Comment by Quicksaver** [comment]
Just to confirm I understood correctly, do you mean when you type "example.org", sometimes you'd like to hit enter and search for that instead of actually going to that address?

**Comment by yfdyh000** [comment]
Yes, sometimes I copied an address from webpage or elsewhere, Press Ctrl+K and Enter key to search it. The urlbar does not provide an entry to search for an address.

**Comment by Quicksaver** [comment]
You're right about this, and I can understand your use-case. But after considering ways to somehow induce this behavior, I can only see introducing new modifier keys and stuff (ctrl+enter, ctrl+shift+enter, some other one), but there are already so many and so many add-ons that changes many of these (and #153 even which only complicates things), I'm definitely not doing that.

The trade-off of using the location bar for both searches and addresses is it has to distinguish between the two, and there's no real way for it to just "know" that you want to search for "example.com" instead of going to that address; after all the rule is if it's an address, go to it. If you find yourself doing web searches like these often, you're probably better off keeping the search bar visible. A unified location bar can't fit every use-case after all. ;)

> It's actually still there are ways, such as use mouse to click on search plugin icon (seem can't to use it with keyboard only)

You can quote it. As in type ```"example.com"```, with the quotes, and it will search for it. Would probably take some time getting used to it and remembering to add the quotes before and after pasting it, but it is keyboard-only. :)

**Comment by yfdyh000** [comment]
Hmmm, the use of quote like a good idea, even if added a `'` to the beginning.

**Comment by Quicksaver** [comment]
You're right, most search engines ignore quotes anyway, especially if they're not closed in pairs, so a single quote anywhere in there should also work just fine.

**Comment by yfdyh000** [comment]
Just learned skill, http://lifehacker.com/5052558/use-a-question-mark-to-search-for-files-in-firefox.

**Comment by Quicksaver** [comment]
Didn't know about that, thanks!
