### ISSUE TITLE
A smaller extension with only the Awesome Bar improvements?

### ISSUE THREAD

**Issue by Gitoffthelawn** [Quicksaver/The-Fox--Only-Better#192]
What do you think of a smaller extension with only the Awesome Bar improvements?

I'm guessing "no", because it's more work... but I figure it never hurts to ask! :+1:

**Comment by Quicksaver** [comment]
It's no, but not because of that, the work would probably be about the same. Right now, if you disable all the features in the add-on you don't want (i.e. Slim Chrome), it won't even be loaded into memory, so it's like it's a stand-alone "Awesome Bar Improvements" add-on already. I'm keeping it all in the same add-on because, at least for now, all these features fit into its overall goal to change/improve the top interface of the window.

**Comment by Quicksaver** [comment]
By the way, two separate add-ons for each feature could not be entirely optimal either, as users who would want the two would have to load the backbone scripts twice (once for each add-on), while like this that only happens once and they can use all those features. ;)

**Comment by Gitoffthelawn** [comment]
Sounds good, and with good rationale.  Thanks!
