### ISSUE TITLE
Wikipedia login unclickable with Slim Chrome enabled

### ISSUE THREAD

**Issue by Exirtis** [Quicksaver/The-Fox--Only-Better#203]
When trying to sign in to Wikipedia today, I found that I couldn't click on "Log In" on the desktop version of Wikipedia (or on the other links next to it on that line).

After some troubleshooting, and testing in another browser, I noticed that nothing that is covered when the toolbars & navigation bars drop down was clickable, while items just below the covered area were. Also significant, and peculiar, is that after I double-clicked the affected area (in an effort to see if the text at least was normally selectable) the browser window un-maximized, as though I had clicked on a title bar.

I turned off slim chrome to confirm this, signed in to Wikipedia, turned slim chrome off again, and found that the previously unavailable items were still selectable. This persisted after logging out of Wikipedia.

While I've never encountered this issue before and have since resolved it, I wanted to let you know about this in case others encounter the same thing.

Some settings:
- Slim Chrome [checked]
- Also hide the navigation bar [checked]
- Show the chrome when the mouse moves to the top  [checked]
- Style [Australis]
- Animation [No animation]

**Comment by EMLVIRUS** [comment]
It works fine for me.
I'm using Beyond Australis 1.4.6 and FF 50.0b4 on Windows 10.14393.
What about your environment.

**Comment by Quicksaver** [comment]
Thank you for the report! It sounds like the add-on had some trouble during initializing Slim Chrome the first time in that session. That's of course not expected. Since this was apparently a one-time thing, there's not much to go on (I've never had this happen to me at least, and I don't recall anyone else reporting it.)

Please do let me know if this starts happening again, especially if you can figure out some specific action that could have caused this in the first place (enabling some add-on, toggling some pref, etc.)

**Comment by Quicksaver** [comment]
The next update will have a few fixes to prevent failures on initialization. Of course I can't be sure they are the same as the ones you experienced, but if you ever see anything like this again please let me know.
