### ISSUE TITLE
Better Compatibility with Classic Theme Restorer's Spacing

### ISSUE THREAD

**Issue by jmain33** [Quicksaver/The-Fox--Only-Better#209]
**In CTR go to the following settings option:**
`Toolbars (1)` :arrow_forward: `Navigation Toolbar` :arrow_forward: `Additional Left and Right Space` :arrow_forward: `Option (2)`

This setting isn't applied properly when using <ins>slim chrome</ins> it ends up working identical to `Option #1` >
Beyond Australis should use `Option #2` to either shrink the navigation bar's overall width, as the setting is intended to do, or just ignore this setting completely while slim chrome is active.

**Comment by Quicksaver** [comment]
Unfortunately there's nothing I can do about that. Because of the way backgrounds are applied in Slim Chrome, there's just no way to avoid that. It also can't "ignore" that setting, because it's a simple CSS statement and overriding that may have complications that, quite frankly, I'm not up to discovering all and fixing all edge-cases that would arise because of it.

Just don't set that setting (it's kinda useless if you consider the point of Slim Chrome anyway, it'll be fine. :smile:

**Comment by jmain33** [comment]
Kept it applied for when I disable slim chrome effect. Since it's (slim chrome) primarily activated I can do without that specific CTR tweak.

Thanks for your time Luís.
