### ISSUE TITLE
Hide the mouse area when showing chrome with mouse is disabled

### ISSUE THREAD

**Issue by f1u77y** [Quicksaver/The-Fox--Only-Better#218]

**Comment by Quicksaver** [comment]
I don't understand. Do you have a problem? Please be more descriptive.

**Comment by f1u77y** [comment]
I have 'Show the chrome when the mouse moves to the top' setting off but I still have a bit of gray area at the top of browser. As I could understand, it's used for activating chrome with mouse but it's useless when the setting is off. So I suggest to hide it(or make an option to hide it) when the setting is off

**Comment by Quicksaver** [comment]
That area has nothing to do with that setting, it's a visual placeholder, so that tabs don't end immediately in the web page. With that setting, the toolbars still show if you move the mouse to the tabs themselves, that area is irrelevant in that case.

You can hide it with something like this in Stylish:
```CSS
#theFoxOnlyBetter-slimChrome-slimmer { display: none; }
```
but you don't really gain anything from doing it, only the three or four pixels in height, and personally I think it looks just bad without it, as the top tabs area won't have a clear limit.
