### ISSUE TITLE
Search Suggestion to Fit awesome bar lenght

### ISSUE THREAD

**Issue by EMLVIRUS** [Quicksaver/The-Fox--Only-Better#219]
See such screen shots below, it can be weird.
![20161210_132204](https://cloud.githubusercontent.com/assets/16912240/21071478/7abafd76-bedc-11e6-9016-76567d17a83a.png)
![20161210_132653](https://cloud.githubusercontent.com/assets/16912240/21071479/7abbefec-bedc-11e6-92eb-96de17e76930.png)

**Comment by Quicksaver** [comment]
That's just how it is ever since Firefox... hum... 48 I believe? I could be wrong about that as I didn't really confirm right now.

Either way, there's a lot going on to style the panel to the full window's width like that. It would take a huge effort to shrink it back to the location bar's width. I don't believe that effort would be worth it, it's barely more than a visual difference, and if anything you'd be losing space in which to show the suggestions.
